# Generated by Django 3.0.8 on 2020-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_auto_20201124_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='educational',
            name='farsi_name',
            field=models.CharField(blank=True, max_length=2018, null=True),
        ),
    ]
