# Generated by Django 3.0.8 on 2020-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('downloads', '0005_auto_20201127_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='url',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]
