# Generated by Django 3.0.8 on 2020-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0007_auto_20201202_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
