# Generated by Django 3.0.8 on 2020-12-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0009_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
