# Generated by Django 3.0.8 on 2020-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0013_auto_20201214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='rating',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
